### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by yunzqq** [denfed/leaf-audio-pytorch#10]
Does it match the performance reported in original leaf paper?

**Comment by denfed** [comment]
It _should_ match the performance in the original paper, but I have not tested that, so no guarantees. I just wanted to quickly create a pytorch implementation, so I made sure the original (TensorFlow) version matched the outputs of this version at every step. _Ideally_ if both implementations output the same result for some audio sample, they should match performance when trained as well.

If someone wants to train and test to compare against the original paper, I would love to include it within this repository.

Thanks!
